Add support for setUid/setGid/Sticky and ACL permissions
xmldb-org/xmldb-api pull request #5
Opened 2022-01-14 21:39 UTC by adamretter

2022-01-14 23:58 UTC, reinhapa requested changes
@adamretter  What is the reason for not using the JDK `java.security.Principal`? The removal of `java.nio.file.attribute` imports make.

2022-01-15 02:40 UTC, adamretter commented
> What is the reason for not using the JDK java.security.Principal?

@reinhapa We seemed to have our own UserPrincipal and GroupPrincipal interfaces which duplicated those of the JDK, so it seemed sensible to be consistent and also duplicate Principal.

2022-01-15 08:50 UTC, reinhapa commented
> @reinhapa We seemed to have our own UserPrincipal and GroupPrincipal interfaces which duplicated those of the JDK, so it seemed sensible to be consistent and also duplicate Principal.

I see your point. I also took a look into some other project as WildFly and  they extended from the Java one also. I would suggest that we rename our "Principal" to something like "AccountPrincipal" just extending the one from the Java JDK so that we got the method definitions from there and still would be able to have common methods for both user/group to be defined on a single place.

2022-01-22 14:34 UTC, reinhapa approved these changes

2022-01-22 14:35 UTC, merged